# Use Node.js base image
FROM node:18

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json first (for caching)
COPY package*.json ./

# Install dependencies
RUN npm install -g ts-node nodemon

# Copy the entire project
COPY . .

# # Build TypeScript
# RUN npm run build

# Expose the port
EXPOSE 8000

# Start the application
CMD ["npm", "run", "dev"]
